// Optional live browser checks: install Playwright, then node tests/browser.cjs.
// ABYSS_CHROMIUM_PATH may point to a local Chromium executable.
const fs=require('node:fs'),path=require('node:path'),http=require('node:http'),assert=require('node:assert/strict');
const {chromium}=require('playwright');
const root=path.resolve(__dirname,'..');
const server=http.createServer((req,res)=>{const pathname=decodeURIComponent(new URL(req.url,'http://localhost').pathname);const file=path.join(root,pathname==='/'?'index.html':pathname);if(!file.startsWith(root+path.sep)){res.writeHead(403).end();return;}try{let content=fs.readFileSync(file);if(file.endsWith('game.js'))content=content.toString().replace(/\}\)\(\);\s*$/,`window.__test={get game(){return game},Enemy,Boss,Weapon,PASSIVES,CURSES,pickup,inventory,saveRun,updateHud,get look(){return {...playerLook}}};})();`);res.setHeader('Content-Type',file.endsWith('.html')?'text/html':file.endsWith('.css')?'text/css':file.endsWith('.svg')?'image/svg+xml':file.endsWith('.js')?'text/javascript':'application/octet-stream');res.end(content);}catch{res.writeHead(404).end();}});

(async()=>{let browser;try{
 await new Promise(r=>server.listen(0,'127.0.0.1',r));browser=await chromium.launch({headless:true,...(process.env.ABYSS_CHROMIUM_PATH?{executablePath:process.env.ABYSS_CHROMIUM_PATH,args:['--no-sandbox','--no-zygote','--single-process','--disable-dev-shm-usage']}: {})});
 const page=await browser.newPage({viewport:{width:1280,height:900}}),errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto('http://127.0.0.1:'+server.address().port);
 const shots=process.env.ABYSS_SCREENSHOTS;async function screenshot(name){if(shots){fs.mkdirSync(shots,{recursive:true});await page.screenshot({path:path.join(shots,name+'.png')});}}
 await page.locator('[data-action=challenges]').click();assert.equal(await page.locator('.challenge-card').count(),8);await screenshot('challenges-locked');await page.locator('#challengeBack').click();
 await page.locator('[data-action=customize]').click();await page.locator('#accessory-hat').selectOption('cap');await page.locator('#accessory-face').selectOption('round');await page.locator('#lookSave').click();assert.deepEqual(await page.evaluate(()=>__test.look),{head:'mint',body:'mint',hat:'cap',face:'round'});
 await page.locator('[data-action=new]').click();assert.equal(await page.evaluate(()=>__test.game.player.weapon.type),'sword');await page.keyboard.press('Tab');assert.equal(await page.evaluate(()=>__test.game.player.weapon.type),'bow');
 await page.keyboard.press('i');assert.match(await page.locator('.reserve-equipment').innerText(),/Épée/);await page.locator('#invSwap').click();assert.equal(await page.evaluate(()=>__test.game.player.weapon.type),'sword');await page.locator('#invClose').click();
 await page.evaluate(()=>{const g=__test.game;g.player.hp=g.player.maxHp=10000;g.player.need=100000;g.player.weapon=new __test.Weapon('laser');g.player.reserveWeapon=new __test.Weapon('axe');g.enterRoom([...g.rooms.values()].find(r=>r.type==='boss'));g.boss.hit(100000,0);__test.updateHud();});assert.match(await page.locator('#bossName').innerText(),/PHASE II/);
 await page.evaluate(()=>{const b=__test.game.boss;b.phaseShift=0;b.pattern=1;b.planAttack();__test.game.paused=true;__test.game.draw();});await screenshot('boss-phase-two');
 await page.evaluate(()=>{const g=__test.game;g.paused=false;g.boss.hit(100000,0);});assert.ok(await page.locator('#bossLoot').isVisible());await page.locator('#bossLoot').click();
 await page.keyboard.press('Escape');await page.locator('[data-p=challenges]').click();assert.equal(await page.locator('.challenge-card.complete').count(),2);await screenshot('challenges-earned');await page.locator('#challengeBack').click();await page.locator('[data-p=customize]').click();await page.locator('#accessory-hat').selectOption('crown');await page.locator('#modalCard').evaluate(e=>e.scrollTop=0);await screenshot('crown-preview');await page.locator('#lookSave').click();await page.locator('[data-p=resume]').click();
 await page.evaluate(()=>{const g=__test.game;__test.pickup({type:'passive',item:__test.CURSES[0],x:400,y:300});});assert.equal(await page.evaluate(()=>__test.game.player.maxHp),7000);await page.keyboard.press('i');assert.match(await page.locator('.cursed-item').innerText(),/CONTREPARTIE/);await page.locator('.cursed-item').scrollIntoViewIfNeeded();await screenshot('cursed-item');await page.locator('#invClose').click();
 await page.evaluate(()=>__test.saveRun());await page.reload();await page.locator('[data-action=continue]').click();assert.equal(await page.evaluate(()=>__test.game.player.reserveWeapon.type),'axe');assert.equal(await page.evaluate(()=>__test.look.hat),'crown');assert.equal(await page.evaluate(()=>__test.game.player.maxHp),7000);
 await page.keyboard.press('Escape');await page.locator('[data-p=challenges]').click();await page.setViewportSize({width:1000,height:650});await page.locator('#challengeBack').scrollIntoViewIfNeeded();assert.ok(await page.locator('#challengeBack').isVisible());assert.deepEqual(errors,[]);
 console.log('Feature browser checks passed: 8 challenge cards, free accessories, Tab and inventory swap, second boss phase, earned rewards, crown preview, curse downside, save/reload and smaller viewport.');
 }finally{if(browser)await browser.close();server.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
