// Run: node tests/regression.cjs (no dependencies needed).
const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict'),path=require('node:path');
const elements=new Map();
function el(key){if(!elements.has(key))elements.set(key,{width:1280,height:720,innerHTML:'',textContent:'',style:{},dataset:{},classList:{add(){},remove(){},toggle(){}},addEventListener(){},getContext(){return new Proxy({createRadialGradient:()=>({addColorStop(){}}),measureText:s=>({width:s.length*7})}, {get:(o,k)=>o[k]||(()=>{})})},querySelector:s=>el(key+' '+s),querySelectorAll(s){return s==='[data-up]'?[0,1,2].map(n=>Object.assign(el('up'+n),{dataset:{up:String(n)}})):s==='[data-shop]'?['charm','gloves','mail','ruby','boots','eye','crown','heart','abyss','fireball','lightning','earth','unlock_laser','unlock_axe'].map(id=>Object.assign(el('buy'+id),{dataset:{shop:id}})):[];}});return elements.get(key);}
const data=new Map(),storage={getItem:k=>data.get(k)||null,setItem:(k,v)=>data.set(k,String(v)),removeItem:k=>data.delete(k)};
const sandbox={document:{querySelector:el,addEventListener(){}},window:{addEventListener(){}},localStorage:storage,Image:class{},performance:{now:()=>1000},requestAnimationFrame(){},queueMicrotask:fn=>{},console,Math,Date};
let source=fs.readFileSync(path.join(__dirname,'../game.js'),'utf8');
source=source.replace(/\}\)\(\);\s*$/,`globalThis.test={settleRoulette,rouletteMultiplier,rouletteColor,startGame,continueRun,saveRun,loadMeta,mainMenu,bankShop,inventory,difficulty,Enemy,Boss,Weapon,pickup,CURSES,ALL_PASSIVES,makeCurseDrop,applyBurn,overload,statusTick,enemySpeed,CHALLENGES,ACCESSORIES,checkChallenges,unlockedAccessory,APPEARANCE,CHARACTER_COLORS,normalizeLook,loadLook,saveLook,drawCreature,get look(){return playerLook},SHOP_ITEMS,SHOP_WEAPONS,ITEM_ART,WEAPONS,money,chooseStartingWeapon,movementSpeed,laserChargeTime,showModal,makeDrop,keys,SPELLS,redeemCheat,mouse,Fireball,SAVE,META,SETTINGS,get game(){return game}};})();`);
vm.createContext(sandbox);vm.runInContext(source,sandbox);const t=sandbox.test;let count=0;
function test(name,fn){fn();count++;console.log('OK '+name);}
function fresh(meta={}){data.clear();storage.setItem(t.META,JSON.stringify(meta));t.startGame();return t.game;}
function bossRoom(g){const r=[...g.rooms.values()].find(r=>r.type==='boss');g.enterRoom(r);return g.boss;}
function finishLevels(g){while(g.levelChoice)el('up0').onclick();}
test('new run has baseline stats and zero money',()=>{const g=fresh();assert.equal(g.player.maxHp,100);assert.equal(g.player.gold,0);});
test('enemy and boss scale beyond three guardians',()=>{fresh();let hp=0,dmg=0,bhp=0;for(const floor of [1,2,3,4,7,10,15]){t.game.floor=floor;const e=new t.Enemy('slime',100,100),b=new t.Boss(0,100,100);assert.ok(e.hp>hp&&e.damage>dmg&&b.hp>bhp);assert.ok(e.speed<=70*1.55);hp=e.hp;dmg=e.damage;bhp=b.hp;}});
test('boss death opens choice, awards soul, cash and clears threats',()=>{const g=fresh(),b=bossRoom(g);g.projectiles.push({});g.hazards.push({});b.die();assert.equal(g.stats.bosses,1);assert.equal(g.player.souls[0],1);assert.ok(g.player.gold>=1500);assert.ok(g.bossChoice&&g.paused);assert.equal(g.hazards.length,0);assert.equal(g.projectiles.length,0);assert.ok(el('#modalCard').innerHTML.includes('Encaisser'));});
test('boss and level up preserve both reward choices',()=>{const g=fresh(),b=bossRoom(g);g.player.xp=g.player.need-1;b.die();assert.ok(g.levelChoice);assert.ok(!el('#modalCard').innerHTML.includes('Encaisser'));finishLevels(g);assert.ok(g.bossChoice&&g.paused);assert.ok(el('#modalCard').innerHTML.includes('Encaisser'));});
test('save/reload while choosing level keeps level and boss choices',()=>{const g=fresh(),b=bossRoom(g);g.player.xp=g.player.need-1;b.die();t.saveRun();t.continueRun();assert.ok(t.game.levelChoice);finishLevels(t.game);assert.ok(t.game.bossChoice);});
test('continue descent keeps cash and soul, raises floor',()=>{const g=fresh(),b=bossRoom(g);b.die();const cash=g.player.gold;g.nextFloor();assert.equal(g.floor,2);assert.equal(g.player.gold,cash);assert.equal(g.player.souls[0],1);assert.equal(g.paused,false);assert.equal(g.bossChoice,false);});
test('bank settlement pays exactly once and ends run',()=>{const g=fresh({bank:300}),b=bossRoom(g);b.die();const cash=g.player.gold;g.cashOut();assert.equal(t.loadMeta().bank,300+cash);assert.equal(t.game,null);assert.equal(storage.getItem(t.SAVE),null);g.cashOut();assert.equal(t.loadMeta().bank,300+cash);});
test('old snapshot cannot cash out again after settlement',()=>{const g=fresh(),b=bossRoom(g);b.die();t.saveRun();const snapshot=storage.getItem(t.SAVE),cash=g.player.gold;g.cashOut();storage.setItem(t.SAVE,snapshot);t.continueRun();assert.equal(t.game.floor,1);assert.equal(t.game.player.gold,0);assert.equal(t.loadMeta().bank,cash);});
test('cashout outside a defeated boss room is rejected',()=>{const g=fresh();g.player.gold=999;g.cashOut();assert.equal(t.loadMeta().bank,undefined);assert.equal(t.game,g);});
test('insufficient funds cannot buy',()=>{fresh({bank:999});t.bankShop();el('buycharm').onclick();assert.equal(t.loadMeta().bank,999);assert.equal(t.loadMeta().owned,undefined);});
test('exact price purchases once and affects only new runs',()=>{fresh({bank:1000});t.bankShop();el('buycharm').onclick();assert.equal(t.loadMeta().bank,0);assert.equal(t.game.player.maxHp,100);el('buycharm').onclick();assert.equal(t.loadMeta().owned.length,1);t.startGame();assert.equal(t.game.player.maxHp,115);});
test('all supreme prices and effects persist without double application',()=>{fresh({bank:1600000});t.bankShop();for(const id of ['crown','heart','abyss'])el('buy'+id).onclick();assert.equal(t.loadMeta().bank,0);t.startGame();assert.equal(t.game.player.maxHp,500);assert.equal(t.game.player.extraProj,2);assert.ok(Math.abs(t.game.player.damageMul-9.6)<1e-8);t.saveRun();t.continueRun();assert.equal(t.game.player.maxHp,500);assert.ok(Math.abs(t.game.player.damageMul-9.6)<1e-8);assert.equal(t.game.player.passives.length,3);});
test('death loses carried cash, preserves bank and owned gear',()=>{const g=fresh({bank:2500,owned:['charm']});g.player.gold=8000;g.player.hp=0;g.gameOver();assert.equal(t.loadMeta().bank,2500);assert.equal(t.loadMeta().owned[0],'charm');assert.equal(storage.getItem(t.SAVE),null);});
test('inventory includes passive effects, stacks and combat stats',()=>{const g=fresh({owned:['crown']});g.player.passives.push('Anneau fendu','Anneau fendu');t.inventory();const html=el('#modalCard').innerHTML;for(const text of ['+6% critique','×2','+60% dégâts','DPS hors critique','Armure','Vol de vie'])assert.ok(html.includes(text),text);});
test('weapon properties survive save and restore exactly',()=>{const g=fresh();g.player.weapon=new t.Weapon('bow',4);g.player.weapon.bonus=2.123;g.player.weapon.extra='speed';t.saveRun();t.continueRun();assert.equal(t.game.player.weapon.bonus,2.123);assert.equal(t.game.player.weapon.extra,'speed');assert.equal(typeof t.game.player.weapon.desc,'function');});
test('boss loot persists after leaving and revisiting room',()=>{const g=fresh(),b=bossRoom(g);b.die();const room=g.room;const drop=g.drops.find(d=>d.type==='weapon');g.enterRoom(g.rooms.get('0,0'));g.enterRoom(room);assert.ok(g.drops.includes(drop));assert.ok(g.drops.some(d=>d.type==='exit'));});
test('version 1 save migrates with same equipment and money',()=>{const g=fresh();g.player.gold=4321;t.saveRun();const s=JSON.parse(storage.getItem(t.SAVE));s.version=1;delete s.runId;storage.setItem(t.SAVE,JSON.stringify(s));t.continueRun();assert.equal(t.game.player.gold,4321);assert.equal(JSON.parse(storage.getItem(t.SAVE)).version,2);});
test('storage failure on cashout retains the run and its cash',()=>{const g=fresh(),b=bossRoom(g);b.die();const cash=g.player.gold,set=storage.setItem;storage.setItem=()=>{throw Error('quota')};g.cashOut();storage.setItem=set;assert.equal(t.game,g);assert.equal(g.player.gold,cash);assert.ok(el('#modalCard').innerHTML.includes('interrompu'));});
test('combat updates and Canvas drawing run at multiple depths',()=>{const g=fresh();g.player.maxHp=g.player.hp=1e12;g.player.dodge=0;for(const floor of [1,4,10]){g.floor=floor;g.paused=false;g.enemies=Object.keys({slime:1,skeleton:1,archer:1,bat:1,mage:1,tank:1,wraith:1,sentinel:1,bomber:1,oracle:1}).map(type=>new t.Enemy(type,620,250));for(let i=0;i<120;i++){g.update(1/60);g.draw();}assert.ok(Number.isFinite(g.player.hp));}});
test('boss choice and loot survive a saved portal return',()=>{const g=fresh(),b=bossRoom(g);b.die();t.saveRun();t.continueRun();assert.ok(t.game.bossChoice&&t.game.paused);assert.ok(t.game.drops.some(d=>d.type==='weapon'));assert.ok(t.game.room.portal);});
test('cheat grants exactly 10M to the bank, is reusable and rejects wrong codes',()=>{fresh({bank:123,owned:['charm']});const carried=t.game.player.gold;t.redeemCheat('nope');assert.equal(t.loadMeta().bank,123);t.redeemCheat(' abysse10m ');assert.equal(t.loadMeta().bank,10000123);assert.equal(t.game.player.gold,carried);assert.equal(t.loadMeta().owned[0],'charm');t.redeemCheat('ABYSSE10M');assert.equal(t.loadMeta().bank,20000123);});
test('cheat storage failure does not claim success or change bank',()=>{fresh({bank:11});const set=storage.setItem;storage.setItem=()=>{throw Error('quota')};const message=t.redeemCheat('ABYSSE10M');storage.setItem=set;assert.ok(message.includes('Impossible'));assert.equal(t.loadMeta().bank,11);});
test('all three spell purchases charge the right prices once and activate on new runs',()=>{fresh({bank:250000});t.bankShop();for(const id of ['fireball','lightning','earth']){el('buy'+id).onclick();el('buy'+id).onclick();}assert.equal(t.loadMeta().bank,0);assert.equal(t.game.player.spells.length,0);t.startGame();assert.equal(t.game.player.spells.length,3);});
function spellArena(){const g=fresh({owned:['fireball','lightning','earth']});g.player.x=400;g.player.y=300;g.player.damageMul=1;g.player.need=100000;t.mouse.x=600;t.mouse.y=300;g.enemies=[];return g;}
function dummy(g,x,y){const e=new t.Enemy('tank',x,y);e.maxHp=e.hp=10000;e.spawn=0;g.enemies.push(e);return e;}
test('unowned and paused spells cannot cast',()=>{const g=fresh();assert.equal(g.player.castSpell('fireball'),false);g.player.spells=['fireball'];g.paused=true;assert.equal(g.player.castSpell('fireball'),false);assert.equal(g.projectiles.length,0);});
test('fireball hits an area once and does not hurt its caster',()=>{const g=spellArena(),a=dummy(g,600,300),b=dummy(g,630,340),far=dummy(g,900,500),hp=g.player.hp;assert.equal(g.player.castSpell('fireball'),true);assert.equal(g.player.castSpell('fireball'),false);const shot=g.projectiles[0];for(let i=0;i<40;i++)shot.update(1/60);assert.equal(a.hp,9910);assert.equal(b.hp,9910);assert.equal(far.hp,10000);assert.equal(g.player.hp,hp);shot.explode();assert.equal(a.hp,9910);assert.equal(g.player.spellCd.fireball,4);});
test('fireball expires with an explosion even without a target',()=>{const g=spellArena();g.player.castSpell('fireball');const shot=g.projectiles[0];for(let i=0;i<100;i++)shot.update(1/60);assert.equal(shot.exploded,true);assert.equal(shot.life,0);});
test('lightning damages at most five distinct enemies with falling damage and stun',()=>{const g=spellArena(),targets=[0,1,2,3,4,5].map(i=>dummy(g,600+i*50,300));assert.equal(g.player.castSpell('lightning'),true);targets.slice(0,5).forEach((e,i)=>{assert.ok(Math.abs(e.hp-(10000-100*.8**i))<1e-6);assert.equal(e.stun,.7);});assert.equal(targets[5].hp,10000);const x=targets[0].x;targets[0].update(.1);assert.equal(targets[0].x,x);assert.ok(targets[0].stun<.7);});
test('lightning without a target consumes no cooldown',()=>{const g=spellArena();dummy(g,200,300);assert.equal(g.player.castSpell('lightning'),false);assert.equal(g.player.spellCd.lightning,undefined);});
test('lightning stuns bosses for a shorter duration',()=>{const g=spellArena(),b=new t.Boss(0,600,300);b.hp=b.maxHp=10000;g.enemies=[b];g.player.castSpell('lightning');assert.equal(b.stun,.25);const x=b.x;b.update(.1);assert.equal(b.x,x);assert.ok(b.stun<.25);});
test('earth clamps its range, deals area damage and grants protection',()=>{const g=spellArena();t.mouse.x=1100;const near=dummy(g,700,300),far=dummy(g,1100,300),hp=g.player.hp;g.player.castSpell('earth');assert.equal(near.hp,9860);assert.equal(far.hp,10000);assert.equal(g.player.ward,1.5);g.player.hit(1000);assert.equal(g.player.hp,hp);assert.equal(g.player.spellCd.earth,10);});
test('spells scale with character damage and have independent cooldowns',()=>{const g=spellArena();g.player.damageMul=2;const e=dummy(g,600,300);g.player.castSpell('earth');assert.equal(e.hp,9720);assert.equal(g.player.castSpell('fireball'),true);g.player.update(1);assert.equal(g.player.spellCd.earth,9);assert.equal(g.player.spellCd.fireball,3);g.paused=true;g.update(1);assert.equal(g.player.spellCd.earth,9);});
test('spell unlocks and cooldowns persist, legacy saves do not gain newly bought spells',()=>{const g=spellArena();g.player.castSpell('earth');t.saveRun();t.continueRun();assert.equal(t.game.player.spells.length,3);assert.equal(t.game.player.spellCd.earth,10);const saved=JSON.parse(storage.getItem(t.SAVE));delete saved.player.spells;delete saved.player.spellCd;storage.setItem(t.SAVE,JSON.stringify(saved));t.continueRun();assert.equal(t.game.player.spells.length,0);assert.equal(Object.keys(t.game.player.spellCd).length,0);});
test('inventory shows owned spell effects and scaled damage',()=>{const g=spellArena();g.player.damageMul=2;t.inventory();const html=el('#modalCard').innerHTML;assert.ok(html.includes('Boule de feu'));assert.ok(html.includes('Chaîne de foudre'));assert.ok(html.includes('Éruption terrestre'));assert.ok(html.includes('Dégâts actuels : 280'));});
test('all spell visuals execute without error in simulated Canvas',()=>{const g=spellArena();dummy(g,600,300);g.player.castSpell('lightning');g.player.castSpell('earth');g.player.castSpell('fireball');g.projectiles[0].explode();g.draw();g.update(1);assert.equal(g.spellEffects.length,0);});
test('currency uses gold coins without changing balances',()=>{fresh({bank:300});assert.equal(t.money(1000),'1 000 PO');assert.ok(!t.redeemCheat('ABYSSE10M').includes('€'));assert.equal(t.loadMeta().bank,10000300);});
test('every passive and shop object has a shipped icon',()=>{const g=fresh();for(const name of ['Anneau fendu','Bottes du rôdeur','Cœur de pierre','Amulette rouge','Cape spectrale','Relique sanglante','Œil du chasseur','Gants véloces','Rune du vent','Carquois double','Cendre vive','Égide ancienne','Fiole verte','Pièce maudite','Crâne explosif',...t.SHOP_ITEMS.map(x=>x.name),...t.SPELLS.map(x=>x.name)]){assert.ok(t.ITEM_ART[name],name);assert.ok(fs.existsSync(path.join(__dirname,'../assets/icons',t.ITEM_ART[name]+'.svg')),name);}});
function equip(g,type){g.player.weapon=new t.Weapon(type,0);g.player.weapon.bonus=1;g.player.weapon.extra=null;g.player.crit=0;g.player.cool=0;g.player.laserCharge=0;}
test('laser deals no damage before charge, then pierces aligned enemies once',()=>{const g=spellArena();equip(g,'laser');const a=dummy(g,550,300),b=dummy(g,800,300),side=dummy(g,600,380),behind=dummy(g,350,300);t.mouse.down=true;g.player.aim=0;g.player.updateLaser(1.3);assert.equal(a.hp,10000);g.player.updateLaser(.1);assert.equal(a.hp,9760);assert.equal(b.hp,9760);assert.equal(side.hp,10000);assert.equal(behind.hp,10000);g.player.updateLaser(.1);assert.equal(a.hp,9760);assert.equal(g.player.cool,.8);t.mouse.down=false;});
test('laser charge cancels on release, pause and weapon pickup',()=>{const g=spellArena();equip(g,'laser');t.mouse.down=true;g.player.updateLaser(.8);t.mouse.down=false;g.player.updateLaser(.1);assert.equal(g.player.laserCharge,0);t.mouse.down=true;g.player.updateLaser(.8);t.showModal('Pause');assert.equal(g.player.laserCharge,0);g.player.laserCharge=.6;t.pickup({type:'weapon',weapon:new t.Weapon('axe'),x:1,y:1});assert.equal(g.player.laserCharge,0);});
test('laser charge resets on load and its type persists',()=>{const g=spellArena();equip(g,'laser');g.player.laserCharge=1;t.saveRun();t.continueRun();assert.equal(t.game.player.weapon.type,'laser');assert.equal(t.game.player.laserCharge,0);});
test('attack speed affects charge time and laser DPS display',()=>{const g=spellArena();equip(g,'laser');g.player.attackMul=2;assert.equal(t.laserChargeTime(g.player),.7);t.inventory();assert.ok(el('#modalCard').innerHTML.includes('0,7 s'));});
test('axe hits every direction including exactly behind, but not distant targets',()=>{const g=spellArena();equip(g,'axe');g.player.aim=0;const ring=[[470,300],[400,370],[330,300],[400,230]].map(([x,y])=>dummy(g,x,y)),far=dummy(g,650,300);g.player.attack();for(const e of ring)assert.equal(e.hp,9948);assert.equal(far.hp,10000);});
test('axe slowdown is reversible, applies to motion, and cannot stack on re-equipping',()=>{const g=spellArena(),base=g.player.speed;equip(g,'axe');assert.equal(t.movementSpeed(g.player),base*.75);t.keys.d=true;const x=g.player.x;g.player.update(.1);delete t.keys.d;assert.ok(Math.abs(g.player.x-x-base*.75*.1)<1e-8);equip(g,'sword');assert.equal(t.movementSpeed(g.player),base);equip(g,'axe');assert.equal(t.movementSpeed(g.player),base*.75);assert.equal(g.player.speed,base);});
test('weapon unlock purchase and starting selection persist and do not grant unowned choices',()=>{fresh({bank:120000});assert.equal(t.chooseStartingWeapon('laser'),false);t.bankShop();el('buyunlock_laser').onclick();assert.equal(t.loadMeta().bank,40000);el('buyunlock_axe').onclick();assert.equal(t.loadMeta().bank,0);assert.equal(t.chooseStartingWeapon('laser'),true);t.startGame();assert.equal(t.game.player.weapon.type,'laser');t.chooseStartingWeapon('axe');t.startGame();assert.equal(t.game.player.weapon.type,'axe');});
test('new weapon visuals and actual passive pickups render with simulated Canvas',()=>{const g=spellArena();equip(g,'laser');t.mouse.down=true;g.player.aim=0;g.player.updateLaser(1.4);g.draw();equip(g,'axe');g.player.attack();g.draw();g.drops=[{type:'passive',item:['Anneau fendu','+6% critique'],x:420,y:300,rarity:2}];g.draw();t.mouse.down=false;});
test('interaction collects only the closest object per keypress',()=>{const g=spellArena();const a={type:'weapon',weapon:new t.Weapon('axe'),x:405,y:300},b={type:'weapon',weapon:new t.Weapon('laser'),x:430,y:300};g.drops=[b,a];t.keys.ePress=true;g.handleInteraction();assert.equal(g.player.weapon.type,'axe');assert.equal(b.taken,undefined);assert.equal(a.taken,true);});
test('merchant transaction saves its purchased state without double charging',()=>{const g=spellArena();const d={type:'weapon',weapon:new t.Weapon('axe'),x:405,y:300,price:100};g.room.shop=[d];g.player.gold=300;t.keys.ePress=true;g.handleInteraction();assert.equal(g.player.gold,200);t.continueRun();t.keys.ePress=true;t.game.handleInteraction();assert.equal(t.game.player.gold,200);assert.equal(t.game.room.shop[0].bought,true);});
test('appearance offers ten unique colors for each of two independent parts',()=>{assert.equal(t.CHARACTER_COLORS.length,10);assert.equal(new Set(t.CHARACTER_COLORS.map(c=>c.id)).size,10);assert.equal(new Set(t.CHARACTER_COLORS.map(c=>c.hex)).size,10);const look=t.normalizeLook({head:'red',body:'blue'});assert.equal(look.head,'red');assert.equal(look.body,'blue');});
test('invalid or missing appearance falls back safely',()=>{fresh();storage.setItem(t.APPEARANCE,'invalid json');assert.equal(t.loadLook().head,'mint');storage.setItem(t.APPEARANCE,JSON.stringify({head:'red',body:'unknown'}));assert.equal(t.loadLook().head,'red');assert.equal(t.loadLook().body,'mint');});
test('saved appearance survives new and resumed games without changing gameplay or bank',()=>{const g=fresh({bank:1234}),hp=g.player.maxHp,damage=g.player.damageMul;t.saveLook({head:'purple',body:'gold'});assert.equal(t.loadLook().head,'purple');assert.equal(t.look.body,'gold');assert.equal(g.player.maxHp,hp);assert.equal(g.player.damageMul,damage);assert.equal(t.loadMeta().bank,1234);t.saveRun();t.continueRun();assert.equal(t.look.head,'purple');assert.equal(t.game.player.maxHp,hp);t.startGame();assert.equal(t.look.body,'gold');});
test('appearance storage failure retains the prior saved colors',()=>{t.saveLook({head:'red',body:'blue'});const set=storage.setItem;storage.setItem=()=>{throw Error('quota')};assert.equal(t.saveLook({head:'gold',body:'green'}),false);storage.setItem=set;assert.equal(t.look.head,'red');assert.equal(t.loadLook().body,'blue');});
test('appearance renderer keeps head and body independent and does not recolor enemies',()=>{function styles(type,look){const values=[];const ctx=new Proxy({}, {get:()=>()=>{},set:(o,k,v)=>{if(k==='fillStyle'||k==='strokeStyle')values.push(v);return true;}});t.drawCreature(type,0,0,44,0,null,look,ctx);return values;}const base=styles('player',{head:'red',body:'blue'});assert.ok(base.includes('#f27e79'));assert.ok(base.includes('#71aaff'));assert.deepEqual(styles('tank',{head:'red',body:'blue'}),styles('tank',{head:'green',body:'gold'}));});
test('two weapon slots start filled and preserve cooldowns when switching',()=>{const g=spellArena();equip(g,'laser');g.player.reserveWeapon=new t.Weapon('axe');g.player.cool=1.2;g.player.reserveCool=.6;g.player.laserCharge=1;assert.equal(g.player.swapWeapon(),true);assert.equal(g.player.weapon.type,'axe');assert.equal(g.player.cool,.6);assert.equal(g.player.reserveCool,1.2);assert.equal(g.player.laserCharge,0);assert.equal(g.player.swapWeapon(),false);g.player.update(.2);assert.equal(g.player.swapWeapon(),true);assert.equal(g.player.weapon.type,'laser');assert.ok(Math.abs(g.player.cool-1)<1e-8);});
test('third weapon pickup leaves the old active weapon on the ground and preserves reserve',()=>{const g=spellArena();equip(g,'axe');const old=g.player.weapon,reserve=g.player.reserveWeapon;g.player.cool=.8;t.pickup({type:'weapon',weapon:new t.Weapon('laser'),x:1,y:1});assert.equal(g.player.weapon.type,'laser');assert.equal(g.player.reserveWeapon,reserve);assert.equal(g.drops.find(d=>d.weapon===old).cool,.8);});
test('both weapon slots and their exact bonuses survive resume',()=>{const g=spellArena();equip(g,'laser');g.player.reserveWeapon=new t.Weapon('axe',4);g.player.reserveWeapon.bonus=2.07;g.player.reserveCool=.75;t.saveRun();t.continueRun();assert.equal(t.game.player.reserveWeapon.type,'axe');assert.equal(t.game.player.reserveWeapon.bonus,2.07);assert.equal(t.game.player.reserveCool,.75);assert.equal(typeof t.game.player.reserveWeapon.desc,'function');});
test('legacy single-weapon save gains a reserve on its next pickup',()=>{fresh();t.saveRun();const saved=JSON.parse(storage.getItem(t.SAVE));delete saved.player.reserveWeapon;storage.setItem(t.SAVE,JSON.stringify(saved));t.continueRun();assert.equal(t.game.player.reserveWeapon,null);const old=t.game.player.weapon;t.pickup({type:'weapon',weapon:new t.Weapon('axe'),x:1,y:1});assert.equal(t.game.player.reserveWeapon,old);});
test('fire burn deals periodic damage and expires',()=>{const g=spellArena(),e=dummy(g,600,300);t.applyBurn(e,18);for(let i=0;i<6;i++)t.statusTick(e,.5);assert.equal(e.hp,9946);assert.equal(e.burnLeft,0);t.statusTick(e,1);assert.equal(e.hp,9946);});
test('lightning consumes burning status and creates one overload per burning target',()=>{const g=spellArena(),e=dummy(g,600,300);t.applyBurn(e,18);g.player.castSpell('lightning');assert.equal(e.hp,9840);assert.equal(e.burnLeft,0);assert.equal(g.stats.combos,1);g.player.spellCd.lightning=0;g.player.castSpell('lightning');assert.equal(g.stats.combos,1);});
test('earth slows enemies and empowers laser hits by 25 percent',()=>{const g=spellArena(),e=dummy(g,600,300);g.player.castSpell('earth');assert.equal(e.slowLeft,4);assert.equal(t.enemySpeed(e),e.speed*.45);equip(g,'laser');g.player.aim=0;t.mouse.down=true;g.player.updateLaser(1.4);t.mouse.down=false;assert.equal(e.hp,9560);assert.equal(g.stats.laserEarth,1);});
test('burn and slow timers are saved and remain paused in menus',()=>{const g=spellArena(),e=dummy(g,600,300);t.applyBurn(e,18);e.slowLeft=4;g.paused=true;g.update(1);assert.equal(e.burnLeft,3);t.saveRun();t.continueRun();assert.equal(t.game.enemies[0].burnLeft,3);assert.equal(t.game.enemies[0].slowLeft,4);});
test('all bosses enforce a second phase, then become vulnerable again',()=>{for(const kind of [0,1,2]){const g=spellArena(),b=new t.Boss(kind,600,300);g.enemies=[b];g.boss=b;b.hit(100000,0);assert.equal(b.hp,b.maxHp*.5);assert.equal(b.bossPhase,2);assert.equal(b.dead,false);b.hit(100000,0);assert.equal(b.hp,b.maxHp*.5);b.update(1.2);b.hit(100000,0);assert.equal(b.dead,true);}});
test('each boss second phase contains new telegraphed patterns',()=>{for(const [kind,type] of [[0,'shockwave'],[1,'sigils'],[2,'roots']]){const g=spellArena(),b=new t.Boss(kind,600,300);g.enemies=[b];b.beginSecondPhase();b.phaseShift=0;b.pattern=1;b.planAttack();assert.equal(b.action.type,type);assert.ok(b.action.left>=.7);if(kind===2)assert.equal(b.action.points.length,5);}});
test('boss warnings do no damage before their countdown finishes',()=>{const g=spellArena(),b=new t.Boss(0,450,300);g.enemies=[b];g.boss=b;b.spawn=0;b.bossPhase=2;b.pattern=1;b.planAttack();const hp=g.player.hp;b.update(.5);assert.equal(g.player.hp,hp);b.update(.51);assert.ok(g.player.hp<hp);});
test('boss phase, warning countdown and damage history survive reload',()=>{const g=fresh(),b=bossRoom(g);b.beginSecondPhase();b.phaseShift=0;b.damageTaken=8;b.pattern=1;b.planAttack();b.action.left=.4;t.saveRun();t.continueRun();assert.equal(t.game.boss.bossPhase,2);assert.equal(t.game.boss.damageTaken,8);assert.equal(t.game.boss.action.left,.4);});
test('legacy boss saves do not incorrectly award a no-hit challenge',()=>{const g=fresh();bossRoom(g);t.saveRun();const saved=JSON.parse(storage.getItem(t.SAVE));delete saved.enemies[0].damageTaken;storage.setItem(t.SAVE,JSON.stringify(saved));t.continueRun();t.game.boss.die();assert.ok(!t.loadMeta().achievements.includes('clean_boss'));});
test('all five cursed relics apply both benefit and downside',()=>{const g=fresh(),p=g.player;t.CURSES[0][2](p);assert.equal(p.damageMul,1.65);assert.equal(p.maxHp,70);assert.equal(p.hp,70);t.CURSES[1][2](p);assert.equal(p.goldMul,1.75);assert.equal(p.eliteBonus,.18);t.CURSES[2][2](p);assert.equal(p.attackMul,1.45);assert.equal(p.healMul,.65);t.CURSES[3][2](p);assert.equal(p.speed,235*1.3);assert.equal(p.incomingMul,1.3);t.CURSES[4][2](p);assert.equal(p.cooldownMul,1.3);});
test('curse cooldown penalty affects spells and inherited boss powers',()=>{const g=spellArena();g.player.cooldownMul=1.3;g.player.castSpell('earth');assert.equal(g.player.spellCd.earth,13);g.player.souls=[1,0,0];g.player.selectedSoul=0;g.player.castSoul();assert.equal(g.player.soulCd[0],10.4);});
test('cursed drop function is restored on resume and remains pickable',()=>{const g=spellArena();g.drops=[{type:'passive',item:t.CURSES[0],x:400,y:300,rarity:3}];t.saveRun();t.continueRun();assert.equal(typeof t.game.drops[0].item[2],'function');t.keys.ePress=true;t.game.handleInteraction();assert.equal(t.game.player.maxHp,70);});
test('free accessories can be saved together, locked rewards cannot be equipped',()=>{fresh();assert.equal(t.saveLook({head:'red',body:'blue',hat:'cap',face:'round'}),true);assert.equal(t.loadLook().hat,'cap');assert.equal(t.loadLook().face,'round');assert.equal(t.saveLook({head:'red',body:'blue',hat:'crown'}),false);});
test('first and clean boss challenges award accessories once and survive death',()=>{const g=fresh(),b=bossRoom(g);b.die();assert.ok(t.unlockedAccessory('party'));assert.ok(t.unlockedAccessory('crown'));const n=t.loadMeta().achievements.length;t.checkChallenges();assert.equal(t.loadMeta().achievements.length,n);g.player.hp=0;g.gameOver();t.startGame();assert.ok(t.unlockedAccessory('crown'));});
test('taking a real hit prevents the clean boss reward, blocked hits do not count',()=>{const g=fresh(),b=bossRoom(g);g.player.dodge=0;g.player.ward=1;g.player.hit(10);assert.equal(b.damageTaken,0);g.player.ward=0;g.player.hit(10);assert.ok(b.damageTaken>0);b.die();assert.ok(!t.unlockedAccessory('crown'));});
test('weapon kill challenge uses the weapon that dealt the lethal hit',()=>{const g=spellArena();equip(g,'axe');g.stats.weaponKills={axe:24};const e=dummy(g,470,300);e.hp=1;g.player.attack();assert.equal(g.stats.weaponKills.axe,25);assert.ok(t.unlockedAccessory('viking'));});
test('laser alignment challenge and remaining run challenges award the right accessories',()=>{const g=spellArena();equip(g,'laser');[550,650,750].forEach(x=>dummy(g,x,300));g.player.aim=0;t.mouse.down=true;g.player.updateLaser(1.4);t.mouse.down=false;assert.ok(t.unlockedAccessory('goggles'));g.stats.combos=10;g.stats.bosses=3;g.floor=5;g.player.passives=t.CURSES.slice(0,3).map(c=>c[0]);t.checkChallenges();for(const id of ['wizard','flower','monocle','halo'])assert.ok(t.unlockedAccessory(id),id);});
test('all accessory drawings execute with the unchanged character renderer',()=>{const calls=[];const ctx=new Proxy({}, {get:(o,k)=>o[k]||(()=>{calls.push(k)}),set:(o,k,v)=>{o[k]=v;return true;}});for(const a of t.ACCESSORIES)t.drawCreature('player',0,0,44,0,null,{head:'mint',body:'mint',[a.slot]:a.id},ctx);assert.ok(calls.includes('ellipse'));});
test('roulette payouts cover all 37 results, including zero',()=>{for(let n=0;n<37;n++){assert.equal(t.rouletteMultiplier('number',n,n),36);assert.equal(t.rouletteMultiplier('number',(n+1)%37,n),0);assert.equal(t.rouletteMultiplier('pair',0,n),n!==0&&n%2===0?2:0);assert.equal(t.rouletteMultiplier('impair',0,n),n%2===1?2:0);assert.equal(t.rouletteMultiplier('rouge',0,n),t.rouletteColor(n)==='rouge'?2:0);assert.equal(t.rouletteMultiplier('noir',0,n),t.rouletteColor(n)==='noir'?2:0);}});
test('roulette rejects invalid stakes and bets without changing bank',()=>{fresh({bank:100});for(const stake of [0,-1,1.5,NaN,Infinity,101])assert.ok(t.settleRoulette(stake,'rouge',0).error);assert.ok(t.settleRoulette(10,'number',37).error);assert.ok(t.settleRoulette(10,'invalid',0).error);assert.equal(t.loadMeta().bank,100);});
test('roulette atomically persists loss and exact number win while preserving upgrades',()=>{fresh({bank:1000,owned:['charm'],achievements:['first_boss']});const random=Math.random;Math.random=()=>0;try{const loss=t.settleRoulette(100,'pair',0);assert.equal(loss.result,0);assert.equal(t.loadMeta().bank,900);const win=t.settleRoulette(100,'number',0);assert.equal(win.payout,3600);assert.equal(t.loadMeta().bank,4400);assert.equal(t.loadMeta().rouletteLast.net,3500);assert.equal(t.loadMeta().owned[0],'charm');assert.equal(t.loadMeta().achievements[0],'first_boss');}finally{Math.random=random;}});
test('roulette failed storage charges nothing and saves no result',()=>{fresh({bank:1000});const set=storage.setItem;storage.setItem=()=>{throw Error('quota')};try{assert.ok(t.settleRoulette(100,'rouge',0).error);}finally{storage.setItem=set;}assert.equal(t.loadMeta().bank,1000);assert.equal(t.loadMeta().rouletteLast,undefined);});
console.log(`${count} regression checks passed.`);
