// Real two-browser integration. Requires Playwright and server npm ci.
const fs=require('node:fs'),path=require('node:path'),http=require('node:http'),assert=require('node:assert/strict');
const {chromium}=require('playwright'),{createRelay}=require('../server/index.cjs');
const root=path.resolve(__dirname,'..');
const screenshotDir=process.env.ABYSS_SCREENSHOTS||path.join(require('node:os').tmpdir(),'abyss-review');fs.mkdirSync(screenshotDir,{recursive:true});
const server=http.createServer((req,res)=>{const pathname=decodeURIComponent(new URL(req.url,'http://localhost').pathname),file=path.join(root,pathname==='/'?'index.html':pathname);if(!file.startsWith(root+path.sep)){res.writeHead(403).end();return;}try{let content=fs.readFileSync(file);if(file.endsWith('game.js'))content=content.toString().replace(/\}\)\(\);\s*$/,`window.__test={get game(){return game},get coop(){return coop},Enemy,Boss,Weapon,PASSIVES,CURSES,coopSerialize,coopFinish,coopDown,coopEvent,coopPersonalLoot,coopSend,coopInput,coopReceive,loadMeta,META,SAVE,get look(){return playerLook}};})();`);res.setHeader('Content-Type',file.endsWith('.html')?'text/html':file.endsWith('.css')?'text/css':file.endsWith('.svg')?'image/svg+xml':file.endsWith('.js')?'text/javascript':'application/octet-stream');res.end(content);}catch{res.writeHead(404).end();}});
(async()=>{let browser,browserGuest,relay;try{
 await new Promise(r=>server.listen(0,'127.0.0.1',r));const origin='http://127.0.0.1:'+server.address().port;relay=createRelay({origins:origin});await new Promise(r=>relay.server.listen(0,'127.0.0.1',r));const ws='ws://127.0.0.1:'+relay.server.address().port+'/coop';
 browser=await chromium.launch({headless:true,executablePath:process.env.ABYSS_CHROMIUM_PATH,args:['--no-sandbox','--no-zygote','--single-process','--disable-dev-shm-usage','--disable-background-timer-throttling','--disable-renderer-backgrounding']});
 browserGuest=await chromium.launch({headless:true,executablePath:process.env.ABYSS_CHROMIUM_PATH,args:['--no-sandbox','--no-zygote','--single-process','--disable-dev-shm-usage','--disable-background-timer-throttling','--disable-renderer-backgrounding']});
 // Two independent browser processes represent two PCs.
 const host=await browser.newPage({viewport:{width:1280,height:900}}),guest=await browserGuest.newPage({viewport:{width:1280,height:900}}),errors=[];
 for(const page of [host,guest])page.on('pageerror',e=>{errors.push(e.message);console.error('PAGE ERROR',e.message)});
 await host.goto(origin);await guest.goto(origin);if(process.env.ABYSS_SCREENSHOTS){fs.mkdirSync(process.env.ABYSS_SCREENSHOTS,{recursive:true});await host.screenshot({path:path.join(process.env.ABYSS_SCREENSHOTS,'solo-lobby.png')});}
 await host.evaluate(()=>{localStorage.setItem(__test.META,JSON.stringify({bank:1200,owned:['unlock_laser','fireball','lightning','earth'],startWeapon:'laser'}));localStorage.setItem(__test.SAVE,'solo-host-must-survive');});
 await guest.evaluate(()=>{localStorage.setItem(__test.META,JSON.stringify({bank:500,owned:['unlock_axe','fireball'],startWeapon:'axe'}));localStorage.setItem(__test.SAVE,'solo-guest-must-survive');});
 for(const [page,name] of [[host,'Joah'],[guest,'Pote']]){await page.locator('[data-action=coop]').click();await page.locator('#coopName').fill(name);await page.locator('#coopServer').fill(ws);}
 await host.locator('#coopCreate').click();await host.waitForSelector('.coop-code');assert.equal(await host.locator('.coop-player-card').count(),2);assert.match(await host.locator('.coop-lobby').innerText(),/Joah[\s\S]*Emplacement libre/);assert.match(await host.locator('.coop-lobby').innerText(),/Joueurs 1 \/ 2/);const code=await host.locator('.coop-code').innerText();await guest.locator('#coopCode').fill(code);await guest.locator('#coopJoin').click();await host.waitForSelector('#coopStart');assert.equal(await host.locator('.coop-player-card.connected').count(),2);assert.match(await host.locator('.coop-lobby').innerText(),/Joah[\s\S]*Pote/);assert.ok(await host.locator('#coopStart').isDisabled());await guest.locator('#coopCustomize').click();await guest.locator('[data-part="head"][data-color="red"]').click();await host.waitForFunction(()=>__test.coop.lobbyPlayers?.[1]?.profile?.look.head==='red');await guest.locator('#lookSave').click();await guest.locator('#coopReady').click();await host.waitForFunction(()=>!__test.coop.lobbyPlayers?.some(p=>!p.profile||!p.ready));assert.ok(await host.locator('#coopStart').isEnabled());assert.ok(await host.locator('[data-coop-lobby-avatar="0"]').evaluate(c=>[...c.getContext('2d').getImageData(0,0,c.width,c.height).data].some((v,i)=>i%4===3&&v>0)));if(process.env.ABYSS_SCREENSHOTS){fs.mkdirSync(process.env.ABYSS_SCREENSHOTS,{recursive:true});await host.screenshot({path:path.join(process.env.ABYSS_SCREENSHOTS,'coop-lobby.png')});}await host.locator('#coopStart').click();
 await guest.waitForFunction(()=>__test.game?.coopPlayers?.length===2);await host.waitForFunction(()=>__test.game?.coopPlayers?.length===2);
 console.log('started');
 // Browser focus produces shared pause by design; explicitly clear between test gestures.
 async function resume(){await host.evaluate(()=>{__test.coop.pauseOwner=null;__test.game.paused=false;});await host.waitForTimeout(100);}
 await resume();assert.equal(await host.evaluate(()=>__test.game.coopPlayers[1].weapon.type),'axe');assert.equal(await guest.evaluate(()=>__test.game.coopPlayers[0].weapon.type),'laser');
 const x=await guest.evaluate(()=>__test.game.player.x);await guest.keyboard.down('d');await guest.waitForTimeout(450);await guest.keyboard.up('d');await guest.waitForFunction(x=>__test.game.player.x>x+20,x);assert.ok(await host.evaluate(x=>__test.game.coopPlayers[1].x>x+20,x));console.log('guest movement');
 await guest.keyboard.press('Tab');await guest.waitForFunction(()=>__test.game.player.weapon.type==='sword');assert.equal(await host.evaluate(()=>__test.game.coopPlayers[1].weapon.type),'sword');
 // Personal loot and guest interaction.
 await host.evaluate(()=>{const g=__test.game,p=g.coopPlayers[1];g.drops.push({type:'passive',item:__test.PASSIVES[0],x:p.x,y:p.y,r:13});__test.coopPersonalLoot();});await guest.keyboard.press('e');await guest.waitForFunction(()=>__test.game.player.passives.includes('Anneau fendu'));assert.equal(await host.evaluate(()=>__test.game.coopPlayers[0].passives.includes('Anneau fendu')),false);console.log('personal loot');
 // Both hit the same authoritative targets, including delayed projectiles.
 await host.evaluate(()=>{const g=__test.game;g.player=g.coopPlayers[0];g.coopPlayers.forEach(p=>{p.need=100000;p.x=500;p.y=350;});const e=new __test.Enemy('tank',570,350);e.hp=e.maxHp=10000;e.spawn=999;g.enemies=[e];});await guest.waitForTimeout(150);await guest.mouse.move(750,440);await guest.mouse.down();await guest.waitForTimeout(700);await guest.mouse.up();assert.ok(await host.evaluate(()=>__test.game.enemies[0].hp<10000));console.log('guest combat');await guest.screenshot({path:path.join(screenshotDir,'coop-combat.png')});
 // Shared pause / inventory must not consume or alter the solo saves.
 await guest.keyboard.press('i');await guest.waitForSelector('[data-coop-event=resume]');assert.equal(await host.evaluate(()=>__test.game.paused),true);await guest.locator('[data-coop-event=resume]').click();await guest.waitForFunction(()=>!__test.game.paused);
 // Revive by holding E for two seconds near the fallen player.
 await host.evaluate(()=>{const g=__test.game;g.enemies=[];const [a,b]=g.coopPlayers;a.x=600;a.y=350;b.x=630;b.y=350;__test.coopDown(a);});await guest.waitForFunction(()=>__test.game.coopPlayers[0].downed);await guest.keyboard.down('e');await guest.waitForTimeout(2450);await guest.keyboard.up('e');await guest.waitForFunction(()=>!__test.game.coopPlayers[0].downed);console.log('revive');
 // Independent level choices, paused until both are done.
 await host.evaluate(()=>{__test.game.coopPlayers.forEach(p=>p.pendingUp++);});await host.waitForSelector('[data-coop-up]');await guest.waitForSelector('[data-coop-up]');await host.locator('[data-coop-up="0"]').click();await guest.locator('[data-coop-up="1"]').click();await guest.waitForFunction(()=>!__test.game.coopPlayers.some(p=>p.choices));console.log('level choices');
 await resume();await host.evaluate(()=>{const g=__test.game;g.player=g.coopPlayers[0];g.enterRoom([...g.rooms.values()].find(r=>r.type==='boss'));});await guest.waitForFunction(()=>!!__test.game.boss);assert.ok(await host.evaluate(()=>__test.game.boss.coopScaled));
 await host.evaluate(()=>{const b=__test.game.boss;b.hit(1e9,0);});await guest.waitForFunction(()=>__test.game.boss.bossPhase===2);await host.evaluate(()=>{const b=__test.game.boss;b.phaseShift=0;b.hit(1e9,0);});await guest.waitForFunction(()=>__test.game.bossChoice);await host.waitForSelector('[data-coop-event=bank]');console.log('boss phase and reward');
 await host.screenshot({path:path.join(screenshotDir,'coop-host.png')});await guest.screenshot({path:path.join(screenshotDir,'coop-guest.png')});
 const balances=await host.evaluate(()=>__test.game.coopPlayers.map(p=>p.gold));await host.locator('[data-coop-event=bank]').click();await guest.waitForSelector('#coopEndBack');await host.waitForSelector('#coopEndBack');assert.equal(await host.evaluate(()=>__test.loadMeta().bank),1200+balances[0]);assert.equal(await guest.evaluate(()=>__test.loadMeta().bank),500+balances[1]);
 assert.equal(await host.evaluate(()=>localStorage.getItem(__test.SAVE)),'solo-host-must-survive');assert.equal(await guest.evaluate(()=>localStorage.getItem(__test.SAVE)),'solo-guest-must-survive');
 await host.locator('#coopEndBack').click();await guest.waitForTimeout(200);assert.equal(await guest.evaluate(()=>__test.loadMeta().bank),500+balances[1]);assert.deepEqual(errors,[]);console.log('Coop integration passed: two independent profiles, input, combat, personal loot, pause, revival, upgrades, boss phases, individual cashout, disconnect and solo-save preservation.');
 }finally{if(browser)await browser.close();if(browserGuest)await browserGuest.close();if(relay)await relay.close();server.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
